macos_arm64:
  name: Build on macOS Apple Silicon (ARM64)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  install_script:
    - brew update
    - brew install gcc zlib
    # Usa il gcc di Homebrew per ARM64
    - export PATH="$(brew --prefix gcc)/bin:$PATH"
    - g++ --version
    - uname -m  # Dovrebbe mostrare arm64
  compile_script:
    - $(brew --prefix gcc)/bin/g++ -Dunix -DSFTP -arch arm64 -DNOJIT zpaqfranz.cpp -o zpaqfranz -pthread -std=c++11 -Wall -Wpedantic 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz

