# Task per Linux
task:
  name: Build on Linux
  container:
    image: gcc:latest
  install_script:
    - apt-get update && apt-get install -y g++ libz-dev
  compile_script:
    - g++ -DSFTP -DHWSHA2 -g -O0 -Wall -Wextra -pthread zpaqfranz.cpp -lm -ldl -o zpaqfranz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz --version
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz

# Task per macOS
task:
  name: Build on macOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  install_script:
    - brew update
    - brew install gcc zlib
    - export PATH="/usr/local/opt/gcc/bin:$PATH"
  compile_script:
    - g++ -DSFTP -DHWSHA2 -g -O0 -Wall -Wextra -pthread zpaqfranz.cpp -lm -ldl -o zpaqfranz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz --version
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz

# Task per FreeBSD
task:
  name: Build on FreeBSD
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y g++ zlib
  compile_script:
    - g++ -DSFTP -DHWSHA2 -g -O0 -Wall -Wextra -pthread zpaqfranz.cpp -lm -ldl -o zpaqfranz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz --version
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz

# Task per Windows
task:
  name: Build on Windows
  windows_container:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    os_version: 2019
  install_script:
    - choco install mingw zlib -y
  compile_script:
    - g++ -DSFTP -DHWSHA2 -g -O0 -Wall -Wextra -pthread zpaqfranz.cpp -lm -o zpaqfranz 2>&1 | tee build_report.txt
  test_script:
    - zpaqfranz.exe --version
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz.exe
