# Alpine Linux - APK based (musl libc - per binari statici)
alpine_task:
  name: Build on Alpine Linux (musl)
  container:
    image: alpine:latest
  install_script:
    - apk add --no-cache g++ musl-dev zlib-dev zlib-static make linux-headers build-base
  compile_script:
    - g++ -DSFTP -DHWSHA2 -static -g -O0 -Wall -Wextra -Wno-stringop-overflow -pthread zpaqfranz.cpp -lz -o zpaqfranz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
