macos_task:
  name: Build on macOS on Apple Silicon
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  install_script:
    - brew update
    - brew install zlib
  compile_script:
    - clang++ -Dunix -DSFTP zpaqfranz.cpp -o zpaqfranz -pthread -std=c++11 -Wall -Wpedantic -lz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
