freebsd13_task:
  name: Build on FreeBSD
  freebsd_instance:
    image_name: freebsd-14-2-release-amd64-ufs
  install_script:
    - pkg install -y clang zlib
  compile_script:
    - clang++ -DHWSHA2 -DSFTP zpaqfranz.cpp -o zpaqfranz -pthread -lstdc++ -lm -lz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
