freebsd13_family_task:
  name: Build on FreeBSD 13 (latest)
  freebsd_instance:
    # Usa la famiglia invece dell'immagine specifica
    image_family: freebsd-13-3
    # Oppure prova con:
    # image_family: freebsd-13-stable
  install_script:
    - pkg install -y clang gcc zlib
  compile_script:
    - c++ -DHWSHA2 -DSFTP zpaqfranz.cpp -o zpaqfranz -pthread -lm -lz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
