# Opzione 1: Usa FreeBSD 14.0 (più recente e probabilmente disponibile)
freebsd14_task:
  name: Build on FreeBSD 14.0
  freebsd_instance:
    image_name: freebsd-14-0-release-amd64
  install_script:
    - pkg install -y clang gcc zlib
  compile_script:
    - c++ -DHWSHA2 -DSFTP zpaqfranz.cpp -o zpaqfranz -pthread -lm -lz 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
