# Task per FreeBSD che va
freebsd14_task:
  name: Build on FreeBSD
  freebsd_instance:
    image_family: freebsd-14-2
  install_script:
    - pkg install -y llvm
  compile_script:
    - cc -O3 -DHWSHA2 -DSFTP zpaqfranz.cpp -o zpaqfranz -pthread -lstdc++ -lm 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz b -debug 2>&1 | tee test_report.txt
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
