# Task per FreeBSD nonva
freebsd14_task:
  name: Build on FreeBSD
  freebsd_instance:
    image_family: freebsd-14-2
  install_script:
    - pkg install -y clang g++ zlib
  compile_script:
    - cc -DHWSHA2 -DSFTP zpaqfranz.cpp -o zpaqfranz -pthread -lstdc++ -lm 2>&1 | tee build_report.txt
  test_script:
    - ./zpaqfranz autotest
  always:
    report_artifacts:
      path: build_report.txt
    executable_artifacts:
      path: zpaqfranz
